### ISSUE TITLE
CLI for all core-infrastructure products: learn more about single-product CLIs

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#101]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/moreinfo_CLI.html

replace
xxxxxxxxx

with introductory text that

    is relevant to all core-infrastructure products
    is useful to readers who may not be knowledgeable about CLIs but who are interested in learning

If appropriate, add to the list of links.

**Comment by rtgoodwin** [comment]
Currently this references RackCLI; should it be tagged for that milestone? Otherwise seems like a duplicate of #106 ? LMK what you think after reading my comments there and what we need to expand.

**Comment by rose-coste** [comment]
started draft, about general practices for product-specific CLIs, at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/moreinfo_CLI.html
