### ISSUE TITLE
CLI for Cloud Servers: demonstrate single-product CLI

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#102]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/cloudservers_CLI.html

replace
xxxxxxxxx

with details about using a product-specific CLI to interact with this product

**Comment by NicoleSchwartz** [comment]
For this the best people to reach out to might be Trey H and Brian R

**Comment by ostackbrian** [comment]
There's an article for this in the KC.  Not sure we want to duplicate in this guide?

http://www.rackspace.com/knowledge_center/article/using-python-novaclient-with-the-rackspace-cloud

**Comment by rose-coste** [comment]
Great; finding the right sources to link to is important help. I'll check this one out.

**Comment by rose-coste** [comment]
updated draft at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/cloudservers_CLI.html, to include link to KC article on python-novaclient
