### ISSUE TITLE
CLI for Cloud Networks: demonstrate single-product CLI

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#103]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/cloudnetworks_CLI.html

replace
xxxxxxxxx

with details about using a product-specific CLI to interact with this product

**Comment by NicoleSchwartz** [comment]
For networks a good person to ask would be sameer s

**Comment by rose-coste** [comment]
copied from https://github.com/rackerlabs/docs-core-infra-user-guide/issues/106, setup for single-product CLIs

Cloud Networks:

    You can use the nova client with Cloud Networks extension, which is required for attaching/detaching networks: http://docs.rackspace.com/servers/api/v2/cs-gettingstarted/content/section_gs_install_nova.html
    Optionally the neutron client can be installed but honestly not entirely clear what benefit that gets you: http://docs.rackspace.com/networks/api/v2/cn-gettingstarted/content/install_neutron.html (install instructions are there, again pip is pretty much the recommendation)

**Comment by rose-coste** [comment]
draft published at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/cloudnetworks_CLI.html and its child, neutron.html
