### ISSUE TITLE
CLI for Cloud Images: demonstrate single-product CLI

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#104]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/cloudimages_CLI.html

replace
xxxxxxxxx

with details about using a product-specific CLI to interact with this product

**Comment by ostackbrian** [comment]
This one could use some docs, but do they belong here or in the KC?
Also, I thought the plan was to push customers toward the rax-cli instead of the raw upstream CLIs?

**Comment by rose-coste** [comment]
rackCLI is not available yet and it'll be a while before it covers these 4 products, so we're documenting the current practice now, coming back later to revise when rackCLI is ready. That's why several CLI-related issues are marked as blocked until the rackCLI milestone: https://github.com/rackerlabs/docs-core-infra-user-guide/milestones/rackCLI%20release

I can publish in the KC and link from here to there if that's the right place for it. We're still working out a plan for which content from the KC should move here and be deleted there. That's a future phase; for now, the project is to find or create the content somewhere.

**Comment by rose-coste** [comment]
copied from https://github.com/rackerlabs/docs-core-infra-user-guide/issues/106, general setup for product-specific CLIs:

Cloud Images:

    client is "python-glanceclient". https://github.com/openstack/python-glanceclient
    the docs for it...are varied and mostly suck. http://docs.openstack.org/developer/python-glanceclient/ is the official one. But there's also another section in the overall OpenStack CLI documentation: http://docs.openstack.org/cli-reference/content/glanceclient_commands.html . The problem is it's both a library and a client, so the docs treat it oddly in some cases.
    installing it should be as easy as "pip install python-glanceclient", or install from the git repo

**Comment by rose-coste** [comment]
draft published at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/cloudimages_CLI.html
