### ISSUE TITLE
CLI for all core-infrastructure products: setup for rackCLI

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#107]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud-interfaces/CLI/index.html, 
rewrite to set expectation of same CLI for all products

in linked-to pages, consider changing section titles to add "rackCLI" references"

**Comment by rose-coste** [comment]
updating link to published draft, changed by https://github.com/rackerlabs/docs-core-infra-user-guide/issues/225

**Comment by stephamon** [comment]
A page about `rack` with links to the proper documentation is in the CLI section and is properly linked to.
