### ISSUE TITLE
GUI for all core-infrastructure products: setup for Cloud Control Panel

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#110]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/setup_GUI.html, 
replace xxxxxxxx
with general information about beginning to use the Cloud Control Panel

**Comment by NicoleSchwartz** [comment]
pinging UX to see if they have ideas - setup itself is sign up via rackspace.com - then you get a first time experience modal (ftx) seeing if we can reuse any of that

**Comment by rose-coste** [comment]
updated draft at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/setup_GUI.html

we can open a new issue if we get more ideas
