### ISSUE TITLE
GUI for Cloud Servers: Cloud Control Panel orientation

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#112]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/cloudservers_GUI.html,
replace xxxxxxxx
with introductory text
* pointing out key ideas in Control Panel related primarily to Cloud Servers and secondarily (via links?)   to other core infrastructure products
* linking to alternative techniques (CLI, SDK+API) & explaining when they might be relevant
* linking to sources of details (KC) and support (Community)

**Comment by rose-coste** [comment]
rackspace.com signup for an account

username + pw set there

low limits; "ask for more" means ticket or call
yellow banner = call us

subuser landing pages depend on access

**Comment by NicoleSchwartz** [comment]
Can users check out community or .com to find out more about ones they aren't sure what they are?

**Comment by rose-coste** [comment]
updated draft at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/cloudservers_GUI.html 

dealing with some comments (subusers, signup,  in updated http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/index.html
