### ISSUE TITLE
GUI for Cloud Block Storage: Cloud Control Panel orientation

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#115]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/cloudblockstorage_GUI.html,
replace xxxxxxxx
with introductory text

* pointing out key ideas in Control Panel related primarily to Cloud Block Storage and secondarily (via links?) to other core infrastructure products
* linking to alternative techniques (CLI, SDK+API) & explaining when they might be relevant
* linking to sources of details (KC) and support (Community)

**Comment by NicoleSchwartz** [comment]
Can users check out community or .com to find out more about ones they aren't sure what they are?

**Comment by rose-coste** [comment]
updated draft at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/cloudblockstorage_GUI.html
