### ISSUE TITLE
No hyperlinks to explain each piece of cloud infrastructure.

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/docs-core-infra-user-guide#139]
This is concerning the first bullet list on the landing page, naming each part of the cloud infrastructure. Changing each of those bullets to a hyperlink that leads to a page that allows a brief, low-level overview of each concept would allow for more clarity. 

I took the liberty of finding a few links to Rackerspace FAQ's regarding each subject. The big issue with each of these link are is that they help with high-level mechanics, but they never give a usable definition. A definition for each term isn't given until the start of the section, "Introducing the Rackspace cloud." 

If the goal is to build confidence through accessibility, than detailed yet simple definitions for each term need to be more accessible. The FAQ pages don't build confidence, ie. The first question on the "Cloud Servers" FAQ link is, "“What if I mess up my cloud server?”. A little terrifying for someone who is just getting started using the Rackspace infrastructure.

Nevertheless, the links, with the parts they define, I found are listed below:

Cloud Servers: (http://docs.rackspace.com/servers/api/v2/cs-gettingstarted/content/overview.html)
	Cloud Networks: (http://www.rackspace.com/knowledge_center/article/cloud-networks-faq) -note, this is a very old article that could stand to be updated, and has a few spelling errors
	Cloud Images: (https://www.rackspace.com/knowledge_center/article/cloud-images-faq#cloud-images)
	Cloud Block Storage: (http://www.rackspace.com/knowledge_center/article/cloud-block-storage-overview)

The last link, for Cloud Block Storage, is the best link. It offers a clear overview of cloud block storage. Couldn't find a link like that one for the other three definitions.

**Comment by DonNateR** [comment]
Possible Solutions:
-Add the brief definitions for Cloud Servers, Cloud Networks, Cloud Images, and Cloud Block Storage to the first page. 

-Create new pages in our knowledge center that gives a more in-depth explanation of each component of the infrastructure. These pages should contain low-level information and lead to more advanced documentation.

**Comment by rose-coste** [comment]
On the front page, I linked to the product marketing pages for each product. They're more than basic definitions, but still fairly introductory. We should think more about when & where (& how: elsewhere, we can provide pop-up tooltips, but I don't know how to do that here) to give basic definitions rather than links to long stories, and we shouldn't lose track of the needed Knowledge Center improvements you noticed (those aren't tracked here, but we can work on them elsewhere).
