### ISSUE TITLE
Better clarification of guide use

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/docs-core-infra-user-guide#140]
In the "How to use guide" page of the infrastructure services user guide, there is a great overview of the contents of the guide via a list of each part of the guide, followed by a brief explanation. The issue is involves the words, "startup process" in the paragraph before the list.

![screen shot 2015-05-27 at 3 54 15 pm 2](https://cloud.githubusercontent.com/assets/12628964/7847427/05e3e396-0489-11e5-952d-b5ba89bc8135.png)

The word, "process" implies that there will be a certain order in how we are supposed to look at the guide. Despite the "next" widget leading to the next page of the guide, I look at the guide and am not sure where to start the process of creating my cloud server. This could be because the guide is actually meant to be used as a reference guide, not a step-by-step process that the reader is meant to follow.

Possible Solution:
-Break the paragraph above the list into smaller sentences. "The guide is meant to simplify your startup process. It doesn't replace our detailed technical documentation, but we hope it gives you a clear picture of what, after getting started, you can do in the Rackspace cloud."  

Breaking up the sentences allows the separate pieces of the guide to stand on their own.

The first allows the reader to know they could go through the guide in order (process). The second tells the reader that the guide can also be used for reference(a clear picture). Furthermore, we start on a positive note, insert the negative(technical documentation) into the middle and end again on another positive.

**Comment by rose-coste** [comment]
new draft at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_guide_intro/index.html, thank you!
