### ISSUE TITLE
Add a colon on Assumptions page

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/docs-core-infra-user-guide#142]
![screen shot 2015-05-28 at 8 52 02 am](https://cloud.githubusercontent.com/assets/12628964/7861624/f3d33786-0516-11e5-93c4-afb5dee146a9.png)
After "...imagining 'you' as someone who" add a colon. Unless there is a grammatical rule about colons after verb subjects that I don't know about.

**Comment by rose-coste** [comment]
repaired by https://github.com/rackerlabs/docs-core-infra-user-guide/commit/ee92dc8fa7c24e8f0e2756b922606a8384679e37, thank you!
