### ISSUE TITLE
Long hyperlink on Rackspace cloud core infrastructure

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/docs-core-infra-user-guide#143]
![screen shot 2015-05-28 at 9 01 08 am](https://cloud.githubusercontent.com/assets/12628964/7861846/1ab528f4-0518-11e5-83f8-3cfb244e8d4b.png)
On the page “Rackspace could core infrastructure at a glance” the sentence, “…read more about Rackspace data centers at http://www.rackspace.com/about/datacenters” isn’t consistent with how the user guide has formatted hyperlinks within the text body. 

Specifically, there was not a full web address in a body paragraph before that. Hyperlinks before this one appeared in body paragraphs like this:
![screen shot 2015-05-28 at 9 05 58 am](https://cloud.githubusercontent.com/assets/12628964/7861973/c4e0f682-0518-11e5-817f-fd27f0e0f194.png)

Despite how useful the link is (the link is another great example of the types of link we should use on the first page explaining each part of Rackspace’s cloud infrastructure), it isn’t consistent with the rest of the document.

Possible Solution: Have the words, “data centers,” before the semi-colon act as a hyperlink. This would make the link consistent with the rest of the guide. Then either delete the clause after the semi-colon, or add a different clause, ie. “;essential to the viability of your cloud.”

**Comment by rose-coste** [comment]
repaired by https://github.com/rackerlabs/docs-core-infra-user-guide/commit/54e60f52ccf67257e3750f95b455a5d2a557c24b, thank you!
