### ISSUE TITLE
Hyperlink on Storage and Content Delivery not highlighted

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/docs-core-infra-user-guide#145]
![screen shot 2015-05-28 at 11 22 12 am](https://cloud.githubusercontent.com/assets/12628964/7865130/20ba0526-052c-11e5-8ee3-5eee1fbfd7dd.png)

Under the "Cloud Files at a glance" subheading on the page "Storage and content delivery" the second bullet contains an inoperable link. The phrase, "PAY only for what you use," should act as the hyperlink for the web address. Likely a small RST error.

**Comment by rose-coste** [comment]
corrected by https://github.com/rackerlabs/docs-core-infra-user-guide/commit/b5feb3d9e6354a2b4c9c33f79f2c13c4d8dbd560, thank you!
