### ISSUE TITLE
Managed Cloud Tour services order and classification

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/docs-core-infra-user-guide#146]
On the “Tour of the managed cloud” page, additional services in paragraph 2 are listed in the order the services may be interacted with when the user access’s our cloud infrastructure. First you need a server, than authentication, storage (recoverability, long-term storage and databases), than a connection and so on. This doesn’t make progression linear, acknowledged by the line, “these services work well the core infrastructure and with each other.”

Thus the order in which these services appear in paragraph 2 doesn’t need to have a natural progression, but the progression helps in understanding their function. 

The issue arises in comparing the order these services appear in paragraph 2, versus the order they appear in the contents. It is indicated in paragraph 3 that “Rackspace could products are grouped so that closely-related products are likely to be discussed together,” hence why the contents section takes the liberty of creating six categories for each product.

So the reader assumes in paragraph 2 that Cloud CDN and Cloud DNS are related, since both services deal function together as a way to connect and load content to public-facing networks. Yet in the contents, Cloud CDN and Cloud DNS appear in separate categories, in opposite order (Cloud DNS appears in Network Services and Cloud CDN appears). 

Possible Solutions:
	-Switch the order of Cloud CDN and Cloud DNS in the paragraph to reflect the table of contents.
	-In paragraph 3, briefly touch on the criteria for why certain services are separated into their respective categories. This could also be done via the individual pages for each category (Compute services, network services, etc.) as well.

![screen shot 2015-05-28 at 11 47 38 am](https://cloud.githubusercontent.com/assets/12628964/7865569/5cf7d6c8-052f-11e5-94b5-a51494a9f958.png)

**Comment by rose-coste** [comment]
new draft at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/cloud_tour/index.html, with services mentioned in order closer to the order in the TOC & other sources. thank you!
