### ISSUE TITLE
Odd wording on "Preparing to use the Cloud Control Panel."

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/docs-core-infra-user-guide#148]
The final sentence on this page could be more specific. The sentence reads, "If you do not have a Rackspace cloud account, or if you have forgotten the account’s credentials, you can use links from the Cloud Control Panel’s login page to get what you need." 

Possible Solution:
-Separate into two distinct sentences, each with an individual link? Like, "If you do not have a Rackspace cloud account, open https://cart.rackspace.com/cloud/?cid=ccpl1. If you have forgotten the account's credentials, click 'Need help logging in', on the Cloud Control Panel's login page, and follow the instructions.
One thing to note is that adding hyperlinks in this way will not be consistent with the formatting of hyperlinks in body paragraphs throughout the guide. I believe that the first link on the page, to the login page, is a justified break from format. The link in the above sentence likely isn't.

**Comment by rose-coste** [comment]
new draft at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/setup_GUI.html, thank you!
