### ISSUE TITLE
All hyperlinks should be embeded

### ISSUE THREAD

**Issue by ianthewhite** [rackerlabs/docs-core-infra-user-guide#151]

**Comment by rose-coste** [comment]
I see URLs in the clear on these pages (making a list here to help make sure I've found & fixed them):

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/cloud_tour/compute_services.html 

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/cloud_tour/network_services.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/cloud_tour/storage_services.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/cloud_tour/data_services.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/cloud_tour/application_services.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/cloud_tour/support_services.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/customer_stories.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/index.html 
(this 1 may be legit)

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/setup_GUI.html
(this 1 may be legit but "credientials" on the same page is surely not)

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/cloudservers_GUI.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/cloudnetworks_GUI.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/cloudimages_GUI.html 

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/cloudblockstorage_GUI.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/GUI/moreinfo_GUI.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/cloudservers_CLI.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/nova.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/supernova.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/cloudnetworks_CLI.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/neutron.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/cloudimages_CLI.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/glance.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/cloudblockstorage_CLI.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/moreinfo_CLI.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/API/devopstools.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/API/SDK.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/API/APIdirect.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/API/cloudservers_API.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/API/cloudnetworks_API.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/API/cloudimages_API.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/API/cloudblockstorage_API.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/API/moreinfo_API.html 

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/compute/cloud_servers_product_concepts/create_server.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/compute/cloud_servers_product_concepts/server_region.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/compute/cloud_servers_product_concepts/metadata/index.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/compute/cloud_servers_product_concepts/boot/cloud-init_boot.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/compute/cloud_servers_product_concepts/nova-agent.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/compute/cloud_servers_product_concepts/time.html
(this 1 may be legit)

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/network/cloud_networks_product_concepts/DNS.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/storage/cloud_block_storage_product_concepts/index.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/storage/cloud_block_storage_product_concepts/disk_storage.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/storage/cloud_block_storage_product_concepts/local_storage.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/storage/cloud_block_storage_product_concepts/software_RAID.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_preprod/security.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_preprod/stack.html 

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_preprod/backups.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_preprod/monitoring.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_preprod/scaling.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/index.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/limits.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/support.html

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/explore.html

**Comment by rose-coste** [comment]
partial solution by https://github.com/rackerlabs/docs-core-infra-user-guide/pull/162; more to come

**Comment by rose-coste** [comment]
partial solution by https://github.com/rackerlabs/docs-core-infra-user-guide/pull/163; more to come

**Comment by rose-coste** [comment]
partial solution by https://github.com/rackerlabs/docs-core-infra-user-guide/pull/164; I think this gets it all, so I'm closing the issue.
