### ISSUE TITLE
Add uniform symbols for each component of cloud infrastructue.

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/docs-core-infra-user-guide#154]
Because the information in the core-infra-user-guide is so dense, there needs to be away to ensure that the dev has a visual reference for what piece of the infrastructure they are working with.
On our landing page for the Support network (http://docs.rackspace.com), we have symbols that correspond with each part of our infrastructure (Cloud Servers, Cloud Networks, Cloud Images, Cloud Block Storage.) Look at the example for the symbol for Cloud Images below:
![cloud image](https://cloud.githubusercontent.com/assets/12628964/7884270/19ecd7bc-05e2-11e5-92f0-fbf7faa99309.png)

We can add these symbols throughout the guide, to give the dev a reminder that they are working with that specific piece of the cloud, with that specific product. Think of it like an insignia for the page, maybe next to the header. I'm working on creating a rough example of what I am talking about.

These symbols can also be used in new visual, as a way to reenforce the central idea of that symbol. We already have an example of this in the guide, 
![2015-05-29_0915](https://cloud.githubusercontent.com/assets/12628964/7884787/e63bf570-05e5-11e5-9d00-d90f0c1b47e3.png)
but this could be improved by making each diagram uniform.

Uniformity is the standard here, between symbols and any new diagrams we create. Working on determining more specific standards.

**Comment by rose-coste** [comment]
I'm working on an infobox to add at the bottom of product-specific pages, showing the product logo & offering links to a few main pages related to that product.

**Comment by rose-coste** [comment]
Experimenting with this on the front page, http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/, which now offers logo+links for 4 products. I imagine the bottom of each product-specific page could include some version of a logo+links box for the relevant product.

**Comment by DonNateR** [comment]
Redrawing every diagram with symbols from the knowledge center.

**Comment by rose-coste** [comment]
Figures now use official product logos, consistent with product logos introduced on the front page. We can plan more use of product logos on product-specific pages later, after we see the document in its new style.
