### ISSUE TITLE
Alternatives and Additional Information Hyperlinks

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/docs-core-infra-user-guide#156]
To ensure uniformity, the hyperlinks on the page below should be embedded.
![screen shot 2015-05-29 at 11 51 29 am](https://cloud.githubusercontent.com/assets/12628964/7887806/864f31ea-05f9-11e5-8237-0d068e109490.png)
Possible Solution:
-Embed the links into each bullet, making the entire clause a link.
-After the comma's on each bullet, use, "start here," embedding the link into the word, "here."

**Comment by rose-coste** [comment]
new draft at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_guide_intro/moreinfo.html, thank you!
