### ISSUE TITLE
add Disqus to every page

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#168]
I created a Disqus forum for this project. The javascript to imbed on every page is at https://github.com/rackerlabs/docs-core-infra-user-guide/blob/master/disqus.html. I just placed on one page, the front page http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/, to make sure it works; it works. 

If there's someplace we're placing other scripts that run on every page (perhaps for Tealium or Google Analytics), this Disqus script should go there. General instructions are at https://disqus.com/admin/universalcode/.

**Comment by annegentle** [comment]
We're dropping Disqus in the new designs; but we want to point to Github issues. That feature won't be available right away, but letting you know the plan for customer feedback loops.

**Comment by rose-coste** [comment]
closed by https://github.com/rackerlabs/docs-core-infra-user-guide/pull/191
