### ISSUE TITLE
Add black border to all screens.

### ISSUE THREAD

**Issue by DonNateR** [rackerlabs/docs-core-infra-user-guide#179]
Add black border to every screenshot in user guide.

**Comment by rose-coste** [comment]
We know where all the screenshots are and where they are used. See the inventory in the README at https://github.com/rackerlabs/docs-core-infra-user-guide/tree/master/screenshots.

**Comment by DonNateR** [comment]
![apikeyscreen](https://cloud.githubusercontent.com/assets/12628964/7922674/6f3b39c8-0873-11e5-82cb-fa4e69112986.png)

Example of screenshot with grey border.

**Comment by DonNateR** [comment]
![resourcelimitsscreen](https://cloud.githubusercontent.com/assets/12628964/7937433/89e5a1ea-0905-11e5-9ed0-f4eac5816579.png)
Example of screen with black bg. Made in Inkscape. RST would require adding a separate background image that could take up the entire page.

**Comment by annegentle** [comment]
Typically you'd do this sort of styling in CSS rather than editing all the images, do you want to give it a try @DonNateR? I can walk you through it.

**Comment by DonNateR** [comment]
I'm down to give it go

**Comment by stephamon** [comment]
Frame is added by the style, so no one has to update images anymore.
