### ISSUE TITLE
add Troubleshooting section

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#181]
We need a section on what can go wrong: 
* how to know it's happening
* how to prevent it
* how to recover from it 
* how to know it's over

Include advice related to specific products and advice related to combinations. 

This is related to, and probably belongs somewhere near, the best practices content that is currently incomplete, noted in https://github.com/rackerlabs/docs-core-infra-user-guide/issues/99.

**Comment by simonjj** [comment]
for now this should be addressed by #200

**Comment by rose-coste** [comment]
draft published at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/troubleshoot.html
