### ISSUE TITLE
Pyrax is mentioned as an example for Python but Pyrax is deprecated

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-core-infra-user-guide#185]
See http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud-interfaces/API/cloudimages-API.html#use-sdk-to-help-you-write-and-run-code-to-interact-with-cloud-images

Security or other critical issues are the only things that will lead to a release of Pyrax. I'd find another example.

**Comment by stephamon** [comment]
@annegentle what is the better alternative? We can't find anything other than Pyrax.

**Comment by stephamon** [comment]
I'm closing out this issue. We're still supporting pyrax in SDK support and on the DRC docs page. If something comes up, I'll open up a new issue.
