### ISSUE TITLE
Table spacing too tight on developer.rackspace.com

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-core-infra-user-guide#187]
For the table on Document History, the text is overlapping the table borders.

**Comment by rose-coste** [comment]
This duplicates https://github.com/rackerlabs/nexus-control/issues/21.

**Comment by rose-coste** [comment]
https://github.com/rackerlabs/nexus-control/issues/21 is closed; tables in this guide now have appropriate padding between text and frame; closing.
