### ISSUE TITLE
When using blockquote, the text is 34 px, should be 14 px

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-core-infra-user-guide#188]
On developer.rackspace.com, blockquote output is too large. Looking at cloud_guide_intro/assumptions.html

**Comment by annegentle** [comment]
Fixed by editing src/site_source/_assets/css/components/docs.less, adding:

```blockquote {
    font-size: 14px;
  }
```

**Comment by rose-coste** [comment]
Closing this issue since it says "Fixed".

**Comment by annegentle** [comment]
Fixed for Nexus with https://github.com/rackerlabs/nexus-control/pull/19
