### ISSUE TITLE
Document History table doesn't need to be maintained going forward; Github is history of record

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-core-infra-user-guide#193]
On the Document History page: http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_guide_intro/document_history.html

there's a table with manual entries about changes to the guide. We haven't been migrating those for the Dev Guides so I'd like to remove for the Infra User Guide as well. We want to have GitHub be the history record for the docs rather than manually editing a table.

**Comment by rose-coste** [comment]
Where will publication dates be visible? As a reader, "how current is this?" is the first thing I want to know; based on that, I can decide whether to bother to read on. 

API devguides have 1 date for the book; KC articles & blog posts & community posts have 1 date per topic; rackspace.com pages have nothing per-topic but © 2015 Rackspace US, Inc. in the footer; api.rackspace.com has ©2014 Rackspace, US Inc. in the footer; https://developer.rackspace.com/docs/auto-scale/getting-started/ has no date that I can see. What will userguides have?

**Comment by rose-coste** [comment]
After consultation with @ianthewhite, https://github.com/rackerlabs/docs-core-infra-user-guide/pull/198 is a compromise solution: 
* begins with a suggestion to look in GitHub and a link there
* continues to the current manually-maintain table, for highlights and big milestones in a format familiar to non-dev readers
That's good enough for now, though ideally I'd like to mark every topic with a tiny revision date to help answer the "is this worth reading?" question easily. Closing this issue.
