### ISSUE TITLE
Storage > Cloud Server Local Storage

### ISSUE THREAD

**Issue by ckuehl** [rackerlabs/docs-core-infra-user-guide#22]
- System disk
 - Data disks
  - Not part of snapshotted images
 - RAID 10
 - Differences between standard and performance flavor classes

**Comment by rose-coste** [comment]
published at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/storage/cloud_block_storage_product_concepts/local_storage.html
