### ISSUE TITLE
standardize font types

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/docs-core-infra-user-guide#268]
Make sure all text formatting (bold, italics, etc) are used consistently throughout guide

**Comment by stephamon** [comment]
Everything is finished, except for italicizing the titles of our other guide books. The problem is that our other books are almost always hyperlinks, so I'm having a hard time getting the link text to italicize.

**Comment by rose-coste** [comment]
Let's not worry about this for now; closing the issue. 

Thanks!
