### ISSUE TITLE
restructure at-a-glance information

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/docs-core-infra-user-guide#296]
rearranging at-a-glance info in the touring service-by-service section into a table with product logo and one-liner

**Comment by stephamon** [comment]
Nearly complete with this, however I'm missing logos for: Cloud CDN, Cloud Feeds, Cloud Metrics, and Object Rocket. Is there a logo for Object Rocket?

**Comment by rose-coste** [comment]
https://github.com/rackerlabs/docs-core-infra-user-guide/pull/318 adds an ObjectRocket logo

**Comment by rose-coste** [comment]
is anything still missing for this?

**Comment by stephamon** [comment]
Cloud Feeds logo is still missing

**Comment by rose-coste** [comment]
I see it in use at http://docs.rackspace.com/ under "Security & Supporting Services"

**Comment by stephamon** [comment]
Yeah, I saw it there, but if I try to just right-click and save, it isn't a very high quality image and it has a white background. If I had photoshop or something, I could fix it myself. Would Lane have it?

**Comment by stephamon** [comment]
FINALLY done! Got Cloud Feeds logo and Rackspace Intelligence added. The logos are a little different from the others (they are in a little blue cloud), but that's what I was given from the Feeds and Intelligence teams, and no other logos exist anywhere else.
