### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by ckuehl** [rackerlabs/docs-core-infra-user-guide#3]
- Make reference to Introduction to Rackspace Cloud guide as a prerequisite
 - What are the Core Infrastructure Services?
  - How do they work together?
  - Multi-tenant OpenStack aaS
 - Brief note on Deployments as an alternative? Possibly also a reference to Heat? Possibly a reference to Auto Scale?

**Comment by rose-coste** [comment]
This core-infrastructure guide has enough in the cloud_intro chapter to stand independently for now; we can strip out that intro when there's a stronger intro elsewhere. Core infrastructure services are listed several places and are bases of the document's structure. References to Auto Scale and to Cloud Orchestration (our implementation of Heat, replacing Cloud Deployments) appear in appropriate locations. Closing the issue as done-enough for now.
