### ISSUE TITLE
standardize text within illustrations

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#309]
in the image at https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-config/network/cloud-networks-product-concepts/network-rackconnect/:

- correct spelling of Enterprise (not Enteprise)
- correct capitalization of SAN (not San)

Throughout the guide, check text in and around (captions and alternate text) images to be sure it is consistent with our writing style.

**Comment by rose-coste** [comment]
look also for internal consistency and parallelism, for example at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud-config/compute/cloud-images-product-concepts/sharing-images/models.html which presents 2 images, one titled "Cloud Image One-to-one sharing" and one titled "Cloud Images handshake"

**Comment by DonNateR** [comment]
Fixed and addressed both issues. With that in mind, we should close this issue out.
