### ISSUE TITLE
investigate status of Cloud Queues

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#349]
Cloud Queues http://www.rackspace.com/en-us/cloud/queues was intentionally omitted from the cloud tour at https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-intro/cloud-tour/. Was that a mistake? Investigate & decide. If appropriate, add Cloud Queues in at least 2 places:

* mentioning its main purpose at https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-intro/cloud-tour/

* introducing it under Application Services, https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-intro/cloud-tour/application-services/, showing its logo (to help with recognizing other Queues doc), linking to pricing info, linking to open-source info (OpenStack Zaqar? Marconi?), linking to product info (https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-intro/cloud-tour/application-services/)

@meker12 is the writer for Cloud Queues and is aware of the question.

**Comment by meker12** [comment]
Someone from Cloud Queues recently contacted us about another issue regarding documentation for AE tokens.  I'll set up a meeting with Balaji Iyer to cover the AE token stuff and to pose this question about whether Cloud Queues should be included in the Cloud Tour. 

Will follow up here when I know more.

**Comment by meker12** [comment]
Closing this.
