### ISSUE TITLE
add rackspace intelligence to cloud tour

### ISSUE THREAD

**Issue by stephamon** [rackerlabs/docs-core-infra-user-guide#350]
belongs with Monitoring (application services?) 

don't call it "Cloud" Intelligence!

**Comment by rose-coste** [comment]
Adding it to the tour means saying just the basics:
* product name
* product logo (the big blue brain visible at http://www.rackspace.com/blog/cloud-monitoring/, but get it from an official source)
* one-line summary
* link to product info (can go to Overview page in KC at http://www.rackspace.com/knowledge_center/article/rackspace-intelligence-overview if there is no official Rackspace product page)
* pricing info (free!)
* open-source info, if any

**Comment by stephamon** [comment]
Rackspace Intelligence added under "Application Services".
