### ISSUE TITLE
integrate contributor doc

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#352]
When it's ready, connect this document to published how-to-contribute doc such as at https://github.com/rackerlabs/docs-how-to-contribute. Good places to connect to contributor guidelines include:
- the site's README at https://github.com/rackerlabs/docs-core-infra-user-guide/blob/master/README.md
- somewhere within the _How to use this guide_ section at https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-guide-intro/

**Comment by DonNateR** [comment]
Still not ready according the repositories ReadME. Will updated once I know more.

**Comment by rose-coste** [comment]
https://github.com/rackerlabs/docs-templates/user-guide/ will be another place to find how-to-contribute guidance
