### ISSUE TITLE
integrate Intro to the Cloud doc

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#355]
The early (2014-04) draft of this infrastructure guide paired it with a general intro to the cloud in a separate document. Development of that companion intro doc was suspended while we pursued the infrastructure doc, and a basic version of that intro exists now within the infrastructure doc, such as at https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-intro/. Still, the early intro doc may contain more ideas we should include here, such as the concepts introduced at https://github.com/rackerlabs/docs-intro-to-rackspace-cloud/blob/master/key_concepts.rst; it's also possible that those ideas are thoroughly covered elsewhere and the most we should do is help readers find them by providing a link. 

Examine the incomplete old intro doc at https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-intro/. If something is mentioned there but not here, decide whether that's OK; if it's not OK, do something about it. Some of what's in the old intro doc is nothing more than a mention, but it can still be valuable as a suggestion of something to develop. An example of this is at https://github.com/rackerlabs/docs-intro-to-rackspace-cloud/blob/master/architecture.rst, pointing out that we should explain our architecture; https://github.com/rackerlabs/docs-core-infra-user-guide/issues/348 says that, too, now suggesting that this project should connect with the reference architectures project that didn't exist when the old intro doc was an active project.

**Comment by stephamon** [comment]
I've added a sentence, plus link to blog post, about "what is managed cloud" on the cloud intro page, increased the info on absolute/rate limits, and added a link to a KC article about regions on the "creating a cloud server in a region" page. 

This takes care of just about all the information listed in the "Key Concepts" page in the docs-intro-to-rackspace-cloud repo.

**Comment by stephamon** [comment]
Closing for now because of the Infrastructure Architecture WS doc restructuring goal.
