### ISSUE TITLE
integrate Knowledge Center content

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#357]
Some content of this guide is very similar to content in the Rackspace Knowledge Center. For example, compare http://www.rackspace.com/knowledge_center/article/available-templates-for-cloud-orchestration and https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-preprod/stack/. 

Draft, coordinate, document, and implement a rational basis for moving content into this userguide (or another future userguide, as suggested by the stubby repos at https://github.com/rackerlabs?utf8=%E2%9C%93&query=user-guide) from its present location in http://www.rackspace.com/knowledge_center/. In support of that, develop a process for maintaining a log of decisions about placement, so we'll have access to our own answers to "why is this here rather than there?" questions.

**Comment by stephamon** [comment]
Closing for now because of the Infrastructure Architecture WS goals.
