### ISSUE TITLE
integrate API doc content 

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#358]
Some content of this guide is very similar to content in API DevGuides and API Getting Started Guides. For example, compare http://docs.rackspace.com/images/api/v2/ci-gettingstarted/content/image-tasks.html and https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-config/compute/cloud-images-product-concepts/import-export-images/.

Some content now in product-specific API DevGuides and API Getting Started Guides is under redevelopment as shared cross-product content in https://github.com/rackerlabs/docs-common. The question applies there, too: is this content about APIs (in which case it might belong in doc focused on  APIs) or about products & services and what they can do (via API or other means, in which case it might belong in a userguide)?

Draft, coordinate, document, and implement a rational basis for moving content into this userguide (or another future userguide, as suggested by the stubby repos at https://github.com/rackerlabs?utf8=%E2%9C%93&query=user-guide) from its present location in http://docs.rackspace.com/ and related collections. In support of that, develop a process for maintaining a log of decisions about placement, so we'll have access to our own answers to "why is this here rather than there?" questions.

**Comment by stephamon** [comment]
Closing for now because of the Infrastructure Architecture WS goal.
