### ISSUE TITLE
confirm consistent use of heading delimiters

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#359]
The heading for every page and every subsection of a page indicates its place within the document's structure by the characters used to underline & overline the heading. 

The characters don't have any meaning of their own: they create order when they are used in a consistent order. http://sphinx-doc.org/rest.html#sections says more about this. 

Make a list of the characters used in section headings at each level of the document. Examine document source to confirm that sections intended to be parallel use the same characters. A map of the document's structure can help in planning this examination; this map was current 2014-06-30, before adding Cloud Files to the guide.
![sitemap-4products](https://cloud.githubusercontent.com/assets/957576/8864612/9af27d46-3169-11e5-9823-34a03dc4b28f.png)

If you find inconsistencies, correct them. 

If Rackspace technical writing standards don't yet define which characters to use in marking which levels of the document, they probably will soon; until then, create order by being consistent within this document. Where Rackspace technical writing standards address this, be consistent with the standards; that may mean helping to develop and document the standards, including any documented at https://github.com/rackerlabs/docs-how-to-contribute. 

Support ongoing development of userguides by making sure we have writer doc that clearly identifies which heading delimiters to use where. Examining the document to see what characters other parallel pages use in headings is a way to discover what will work, but we should offer something easier.

**Comment by stephamon** [comment]
Okay, I tracked all the heading styles and there are definitely some inconsistencies in the way each level of header is structured. I think what I'll do is go through and make it like this for the header levels:

1  ======
2  ------
3  ^^^^^^
4  ~~~~~~
5  ++++++

**Comment by rose-coste** [comment]
@stephamon, I see why you're still not getting the concept details to operate as children of the main Cloud Files Concepts page. You can fix this!

At /infrastructure/cloud-config/storage/cloud-files-product-concepts/index.rst, you have a subsection titled "Ideal Uses for Cloud Files". Break that out into a separate page, add that new page to the toctree for /cloud-files-product-concepts/index.rst, and it'll clean up. 

This is exactly what broke & how I fixed it (after moving to developer.rackspace.com; Read the Docs didn't mind) in the Cloud Networks concepts section. Look at how https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-config/network/cloud-networks-product-concepts/ relates to https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-config/network/cloud-networks-product-concepts/cloudnetworks-usecases/; Usecases was once a section on the main Concepts page, but now that they are separate files, the TOC is working just fine.

**Comment by stephamon** [comment]
@rose-coste, you are a genius! That finally fixed the navigation issue!

**Comment by stephamon** [comment]
I'm going to close this. The entire book follows this for page headers:

1 ======
2 ------
3 ^^^^^^
4 ~~~~~~
5 ++++++
