### ISSUE TITLE
add link to edit on GitHub

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#412]
adapt from DevGuides, for instance https://github.com/rackerlabs/docs-cloud-backup/blob/master/api-docs/cloud-backup-v2/_deconst.json

**Comment by rose-coste** [comment]
https://github.com/rackerlabs/docs-core-infra-user-guide/pull/413 (merged) sets up to use https://github.com/rackerlabs/nexus-control/issues/295 when it is ready

**Comment by stephamon** [comment]
Fixed by https://github.com/rackerlabs/nexus-control/pull/307
