### ISSUE TITLE
resynch with Support doc after migration to how-to

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#414]
- new location is https://support.rackspace.com/how-to/
- old location was https://www.rackspace.com/knowledge_center/

In conf.py, find **extlinks**, change these:

 -   'kc': ('http://www.rackspace.com/knowledge_center/%s', ''),
 -   'kc-article': ('http://www.rackspace.com/knowledge_center/article/%s', ''),
 -   'kc-faq': ('http://www.rackspace.com/knowledge_center/frequently-asked-question/%s', ''),
 -   'kc-product-faq': ('http://www.rackspace.com/knowledge_center/product-faq/%s', ''),

Then check & fix throughout the guide: many articles have new filenames within the new site.

**Comment by stephamon** [comment]
Done with #418
