### ISSUE TITLE
Dead link on Cloud Files' Web Acceleration page

### ISSUE THREAD

**Issue by dragorosson** [rackerlabs/docs-core-infra-user-guide#421]
On https://developer.rackspace.com/docs/user-guides/infrastructure/cloud-config/storage/cloud-files-product-concepts/web-acceleration/ there is a note about CNAMEs:

> You can use CNAME records to link your Cloud Files container to a branded URL that you display instead of a CDN URL. To learn more about CNAMEs, check out Using CNAMEs with Cloud Files containers.

Which goes to http://www.support.rackspace.com/how-to/using-cnames-with-cloud-files-containers. However, this 404s.

**Comment by dragorosson** [comment]
It appears that the similar URL https://support.rackspace.com/how-to/using-cnames-with-cloud-files-containers/ works.

**Comment by stephamon** [comment]
@dragorosson thanks for pointing this out! It looks like the link requires the trailing slash now. We've made some changes to how the How-To site is served recently. I'll correct this one and go through the guide to make sure the other How-To links are right.

**Comment by dragorosson** [comment]
@stephamon Welcome. The trailing slash doesn't appear to make a difference. Instead, `www` must be removed.

**Comment by stephamon** [comment]
@dragorosson Ah, I see. Fortunately that's a much quicker fix!
