### ISSUE TITLE
Cloud Servers > Commit, Volume, and Prepayment Discounts

### ISSUE THREAD

**Issue by ckuehl** [rackerlabs/docs-core-infra-user-guide#49]
Rackspace offers several ways to receive discounts on your cloud services. Discounts apply to your aggregated monthly spend on all flavors of Cloud Servers within a specific geography (e.g. the United States). Changing flavors or US region will not affect your discount eligibility.

TODO: Add details about each specific discount

To learn more about discounts visit `Discounts for Cloud Servers <http://www.rackspace.com/cloud/servers/discounts/>`_.

**Comment by rose-coste** [comment]
after discussion at March 2 status meeting, sales-related content seems beyond the scope of this document
