### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by ckuehl** [rackerlabs/docs-core-infra-user-guide#7]
- Sending mail (IP reputation; use Mailgun instead)
 - Using config drive and cloud-init to bootstrap (base images versus snapshots for build-time performance)
 - Use SSH keys vs. password for Linux
 - Use ServiceNet for Cloud Files and Cloud Databases, use Cloud Networks for server to server communication
 - For Cloud Networks, use RFC 1918 less the two ServiceNet blocks
 - Recommendations for image use
  - Use UUID for complete consistency
  - Use ??? to get latest and greatest of same minor version (CentOS 5.1)
  - Use ??? to get latest and greatest of same major version (CentOS 5.x)
  - Use ??? to get latest and greatest of same OS (latest CentOS)

**Comment by rose-coste** [comment]
published at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/explore.html#best-practices
