### ISSUE TITLE
metadata: improve list formatting

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#72]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/compute/cloud_servers_product_concepts/metadata/set_metadata.html?highlight=metadata

standarize bolding and indentation for this bulleted list item:

view the image properties of the image and look for fields prefixed
with instance

**Comment by ostackbrian** [comment]
About this:
"view the image properties of the image and look for fields prefixed with instance"
The context is recovering server metadata that you have deleted.  Server metadata is not passed onto on-demand images of a server, so the suggestion won't work.  What the instance_ image metadata are, are specific properties of the server.  Here's an example of a server with some metadata on it, followed by a snapshot image of the server:
::
    $ nova show 161ecc6d-a4aa-4cdd-979f-536c55857c90
    +--------------------------------------+------------------------------------------------------------------------------+
    | Property                             | Value                                                                        |
    +--------------------------------------+------------------------------------------------------------------------------+
    | created                              | 2014-11-18T22:02:06Z                                                         |
    | flavor                               | 1 GB General Purpose v1 (general1-1)                                         |
    | id                                   | 161ecc6d-a4aa-4cdd-979f-536c55857c90                                         |
    | image                                | Ubuntu 14.10 (Utopic Unicorn) (PVHVM) (0766e5df-d60a-4100-ae8c-07f27ec0148f) |
    | metadata                             | {"build_config": "core"}                                                     |
    | name                                 | MyServer                                                                     |
    | status                               | ACTIVE                                                                       |
    +--------------------------------------+------------------------------------------------------------------------------+

::
    $ nova image-show 6a3dc9f2-c82b-486e-8d24-4962062582a3
    +------------------------------------------------+--------------------------------------+
    | Property                                       | Value                                |
    +------------------------------------------------+--------------------------------------+
    | metadata instance_type_ephemeral_gb            | 0                                    |
    | metadata instance_type_flavorid                | general1-1                           |
    | metadata instance_type_id                      | 56                                   |
    | metadata instance_type_memory_mb               | 1024                                 |
    | metadata instance_type_name                    | 1 GB General Purpose v1              |
    | metadata instance_type_root_gb                 | 20                                   |
    | metadata instance_type_rxtx_factor             | 200.0                                |
    | metadata instance_type_swap                    | 0                                    |
    | metadata instance_type_vcpu_weight             | 10                                   |
    | metadata instance_type_vcpus                   | 1                                    |
    | metadata instance_uuid                         | 161ecc6d-a4aa-4cdd-979f-536c55857c90 |
    +------------------------------------------------+--------------------------------------+

**Comment by ostackbrian** [comment]
Anyway, I will put in a pull request to remove the text that offends me.  Just put the details above so that you'll understand the situation.

**Comment by rose-coste** [comment]
Thanks, Brian. I added a Cloud Servers tag here to show there's an issue of content, too; I'll wait to deal with the formatting issue until I see the new content.

**Comment by rose-coste** [comment]
closed by pull request, https://github.com/rackerlabs/docs-core-infra-user-guide/pull/123
draft updated at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/compute/cloud_servers_product_concepts/metadata/set_metadata.html 

Thanks, Brian!
