### ISSUE TITLE
APIs & SDKs for all core-infrastructure products: setup

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#83]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/API/setup_API.html 

replace
xxxxxxxx
and the 2 short lines below it

with a useful explanation, relevant to all core-infrastructure products, of how to prepare to work with APIs and SDKs.

identify basic steps such as obtaining an API key and downloading an SDK.

don't duplicate what exists elsewhere, but point it out: identify what we have and which resource is most useful for which purpose

**Comment by rtgoodwin** [comment]
A lot of this seems to be covered at: https://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/API/index.html#software-development-kits-sdks 

Do we integrate that, or summarize, or expand? Hate to just rewrite for fun. I'm still looking for the best doc on API key, but one of these is probably fine:
* http://www.rackspace.com/knowledge_center/article/view-and-reset-your-api-key
* http://www.rackspace.com/knowledge_center/video/how-to-view-your-account-api-key  (videos can get outdated though...)

**Comment by rose-coste** [comment]
Chrome 
View
Developer
Developer Tools
network tab
turn on to see API calls used in Control Panel

**Comment by rose-coste** [comment]
Thanks,  @rtgoodwin, your question helped me figure out what I wanted to do differently in introducing the general idea of an API as one way of interacting with a service, versus introducing a generalizable approach to working with Rackspace APIs, versus introducing specifics per each API

https://github.com/rackerlabs/docs-core-infra-user-guide/pull/126 publishes several improvements related to all that; closing this issue until we come around again and improve the improvements.
