### ISSUE TITLE
intro to core infrastructure: replace drawing

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#84]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/core_infrastructure.html

replace the placeholder drawing with a drawing focused on the core-infrastructure products, with a textual explanation directly related to it

**Comment by rose-coste** [comment]
Anand is coordinating this.

**Comment by rose-coste** [comment]
I hid the placeholder drawing to make the page more readable for now; it still needs a replacement.

**Comment by simonjj** [comment]
Based on an initial sketch Nate should have a diagram we can iterate on tomorrow.

**Comment by DonNateR** [comment]
![infradiagramdraft1](https://cloud.githubusercontent.com/assets/12628964/7962861/6ea0b75a-09d5-11e5-8a79-e8a6fe23c02f.png)
First draft of new diagram.

**Comment by DonNateR** [comment]
![infradiadraft2](https://cloud.githubusercontent.com/assets/12628964/7966027/f41136b0-09e6-11e5-9944-28a44fc7903e.png)

Here is the second iteration using feedback from some of the DevDoc's team.

**Comment by stephamon** [comment]
Are the dotted lines meant to be going through or behind the Cloud Networks?

**Comment by DonNateR** [comment]
Through

**Comment by DonNateR** [comment]
Here is the third iteration. 

![infradiadraft6wbg](https://cloud.githubusercontent.com/assets/12628964/7987781/3b992ee8-0aa5-11e5-9cde-f10389c6ec4d.png)

**Comment by rose-coste** [comment]
I published the new drawing to http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/core_infrastructure.html & noted it in the figures inventory at https://github.com/rackerlabs/docs-core-infra-user-guide/blob/master/figures/README.md. 

Closing the issue but you are free to continue refining the drawing, its caption, its placement (centering also centers the caption, so I'm not sure that should be our standard), its size (:scale: directive is ignored so I resized it with SnagIt for now; http://docs.readthedocs.org/en/latest/faq.html#image-scaling-doesn-t-work-in-my-documentation may explain)
