### ISSUE TITLE
intro to application services: add Cloud Metrics

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#85]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/cloud_tour/application_services.html

replace xxxxxxxx
with
details about Cloud Metrics

**Comment by rose-coste** [comment]
Cloud Metrics overview added to KC last week at http://www.rackspace.com/knowledge_center/article/cloud-metrics-overview is usable as a substitute for the formal product page

no charge, like Cloud Monitoring?

**Comment by wolfdancer** [comment]
No charge.  It is built on top of blueflood (http://blueflood.io/). Blueflood itself is built on top of Cassandra.

**Comment by rose-coste** [comment]
Thanks, Shane, added this new info to the page at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/cloud_tour/application_services.html#cloud-metrics-at-a-glance and am closing the issue.
