### ISSUE TITLE
best practices: Cloud Images UUID

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#86]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/explore.html

replace
xxxxxxxx (3 times)
with details about the best practice for using UUID to maintain consistency

**Comment by ostackbrian** [comment]
This is a huge can of worms, probably needs its own KC article about finding the latest image for the 3 examples given.

For this one, I'd say:

For Cloud Images, use the UUID where possible because the UUID of an image cannot change, whereas the name cannot be guaranteed to be constant.

**Comment by rose-coste** [comment]
closed by pull request, https://github.com/rackerlabs/docs-core-infra-user-guide/pull/122 
draft updated at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/explore.html
