### ISSUE TITLE
adding cloud services: explain how

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#87]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/limits.html?highlight=xxxxxxxx#adding-services 

replace
xxxxxxxx

with 
details on how to sign up for new cloud services that you didn't sign up for when you created your cloud account, either because they didn't interest you or they didn't exist at the time

**Comment by rose-coste** [comment]
create support ticket

**Comment by NicoleSchwartz** [comment]
Context: all products when they go general availability should be added to everyone's catalog. to ask about a beta or something that for some reason got missed on your account support can find the right person to add a new entry to your service catalog (whole product) - if on the other hand you have the product but not ENOUGH of the product (limit) make a request to increase your quantity to support

**Comment by rose-coste** [comment]
updated draft at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/limits.html
