### ISSUE TITLE
intro to security services: add Cloud Feeds

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#88]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/cloud_tour/support_services.html?highlight=xxxxxxxx#cloud-feeds-at-a-glance 

add details about Cloud Feeds

**Comment by rose-coste** [comment]
no product page that I can find, but the KC intro at http://www.rackspace.com/knowledge_center/article/cloud-feeds-overview might be the right source of a product overview

**Comment by rose-coste** [comment]
pricing info at http://www.rackspace.com/knowledge_center/article/cloud-feeds-faq#cost says "no charge". with this, I can update the text and close the issue.

**Comment by rose-coste** [comment]
draft published at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_intro/cloud_tour/support_services.html#cloud-feeds-at-a-glance

**Comment by pakazmir** [comment]
@rose-coste  I'm the Product Manager for Feeds, can I help you with anything? I checked the draft, and it looks fine to me.

**Comment by rose-coste** [comment]
Hi, Peter, I think this minimal intro to Feeds is all we need for now, but thanks for checking; I'll find you if that changes.
