### ISSUE TITLE
Limits: improve table format

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#92]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/limits.html, 
the table is readable as HTML 
but 
not readable in the PDF at https://media.readthedocs.org/pdf/rackspace-core-infra-user-guide/latest/rackspace-core-infra-user-guide.pdf (page 63 of the 2015-04-21 version).

usually, tables look wrong because long text doesn't wrap within cells. 
here, the table format is garbled after the header. 

what's up with that?

**Comment by NicoleSchwartz** [comment]
Also MyCloud has a "resource limits" page under the account menu with servers (and soon to be CBS) - if customers ask about another product let us know and we can add that too https://mycloud.rackspace.com/account#resource-limits

**Comment by rose-coste** [comment]
updated draft at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/limits.html; table is readable now in both HTML & PDF.
added content about resource limits
