### ISSUE TITLE
standardize handling of figures & screenshots

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#93]
the figures inventory is at https://raw.githubusercontent.com/rackerlabs/docs-core-infra-user-guide/master/figures/README.md

the screenshots inventory is at https://raw.githubusercontent.com/rackerlabs/docs-core-infra-user-guide/master/screenshots/README.md

for all figures and screenshots:

* establish standards for use (when do we need a screenshot? when do we need a figure?)
* establish standards for titles, captions, size, placement, highlighting, visual vocabulary
* document the standards someplace accessible to everyone who can access the repo
* implement the standards

**Comment by rose-coste** [comment]
I added an "illustrations" label to mark issues related to this.

**Comment by DonNateR** [comment]
While this doesn't solve the issue, here are few standards we could establish for screenshots:

-Grey (charcoal grey) border for all screenshots. This darker grey will contrast with the light grey of our GUI.
-Captions appear beneath screenshot.
-Caption will be in smaller font than body paragraphs.
-Captions will be italicized.

Still working on standards for placement, other standards within screenshots, and standards for diagrams and other visual cues. Will update when determined.

**Comment by rose-coste** [comment]
Some formatting matters are beyond our direct control, or should be since we should rely on the site-wide style to define them. For example, https://github.com/rackerlabs/docs-core-infra-user-guide/issues/171 notes that the appearance of captions needs styling, & I tagged it for the "Rackspace style" milestone as a reminder to follow that up when we're on our own site rather than Read The Docs". I'm tagging this one the same way now, for the same reason.

**Comment by DonNateR** [comment]
Example of grey border, with new screenshot for API key.
![rect5747](https://cloud.githubusercontent.com/assets/12628964/7922620/18edcd88-0873-11e5-9a54-b9ff18bc38a7.png)

**Comment by rose-coste** [comment]
@DonNateR, does everything we have now follow your standards? If so, please close this. 
Thanks.
