### ISSUE TITLE
best practices: expand

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#99]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_ops/explore.html#best-practices, expand the list of suggestions to include more

* specific actions, possibly with links to detailed demonstrations elsewhere (Community? KC?)
* focused on core-infrastructure products or generalizable to all products

Create order within the list; now, it's random deep thoughts.

**Comment by rose-coste** [comment]
Anand is coordinating this.

**Comment by simonjj** [comment]
Pull #182 should take care of this

**Comment by rose-coste** [comment]
This is very much improved: more useful and more organized. I'm closing the issue. If we think of more good advice, we can expand the page in the future.
